sudo: required

language: python

notifications:
  email: false

python:
  - "2.7_with_system_site_packages"

before_install:
  - git clone https://github.com/ethereum/serpent
  - cd serpent && make && sudo make install && sudo python setup.py install && cd ..

install:
  - pip install -U pip
  - pip install ethereum -r test_requirements.txt

script:
  - py.test tests/trading_tests.py
